gossip3to4/node.go, gossip4/node.go, gossip4/txvalidator.go, gossip4/txvalidator_test.go
oops - we were just sending gossip3tx directly into himitsu instead of validating they were OK. This does the validation. 
A couple o' notes: 
* this will conflict (lightly) with #369 , but should be easy to fix up
* any ChainTree with state over in gossip3 land will not validate in gossip4 (I think that's OK for now but wanted to note)
* I opted to send in the tx from the gossip3to4 module rather than using the Tx validator's own send mechanism, because otherwise this would have to reserialize the new AddBlockRequest and convert it to a pubsub message and then send it over which feels more complicated.
* You can't just re-publish the new message because then every gossip4 node would rebroadcast every Tx... so you do need to keep it within the single node.
=> actually validate the gossip3 incoming transactions

cmd/node.go, configs/localdocker/rpcserver/config.toml, docker-compose.yml, gossip/node.go, gossip/node_test.go, nodebuilder/nodebuilder.go
Discovered this when starting up trying to re-do the wasm directory. 
This:
* use the destkey for the p2p node key (only way it will be reachable)
* turn on websockets for bootstrap / g4 nodes
* use notary group config for the transaction topic (stop hard-coding)
* other very minor cleanups (10s bootstrap, change order of bootstrapping, etc)
=> config improvements

gossip/node_test.go, gossip/txvalidator_test.go, nodebuilder/nodebuilder_test.go
master had a failing CI - my guess is that the old system hadn't fully shut down when the new one is spinning up and so there is a naming conflict. This gives every system a new name so they don't conflict.
=> name the tupelo systems different things so they don't conflict

cmd/node.go, configs/localdocker/localdocker.toml, go.mod, go.sum, gossip/node.go, nodebuilder/nodebuilder.go
smallish changes (one is bringing in tupelo-go-sdk master though) that I noticed while building out the wasm restore.
=> wasm changes

go.mod, go.sum, nodebuilder/nodebuilder.go
Small change to account for removing the `...gossip/middleware` package from tupelo-go-sdk.
=> use go-log for all logging

gossip/node.go, gossip/txvalidator.go, gossip3to4/addblockrequest.go, gossip3to4/addblockrequest_test.go
Branch name is kind of misleading. There's nothing wrong with the gossip4 validator. Just needed to teach it how to ignore the `NewTip` property of converted gossip3 ABRs.
=> Fix gossip4 validator

gossip/node.go, gossip/sigverifier.go, gossip/snowballnetwork.go
given the observability that we were missing for @cap10morgan , this adds a "stop tracing" to any errors coming in on the handleAddBlockRequest.
I also realized we weren't tracking any snowball runs, this adds the most basic "time how long a snowball takes" so at least we can see it running.
=> add tracing to snowballer, stop trace one wrapper for errors

gossip/benchmark/benchmark.go, gossip/benchmark/benchmark_test.go
this is a port of the cmd/benchmark.go code over here into a package that can be tested. cmd would then use this to do the json output, etc.
=> add a benchmark package and test

nodebuilder/nodebuilder.go
this is my bad. @cap10morgan was seeing a nil PID on the g3->g4 subscriber and then I realized that we never actually set the PID here, so when the actor went to send the message, it was nil and errored.
=> actually set the actor PID on start

Dockerfile, docker/docker-entrypoint.sh, go.mod, go.sum
About to deploy this to make sure it works. There will be an upcoming PR in tupelo-infrastructure to set `TUPELO_ADVERTISE_EC2_PUBLIC_IP` to `true`.
Has #392 in it too. Sorry about that.
=> Set EC2 public IP

go.mod, go.sum
To get tracing.LogKV that delegates to SetTag so they will actually show
up in ELK.
=> Update tupelo-go-sdk to latest master

gossip/node.go, gossip/rounds.go, gossip/rounds_test.go
from chat:
```
still seeing here: 13:34:18.588 WARNI     node-3: error creating stream to 0x7D3299C2a7304Fd74074af30785724C79A775d42: dial backoff snowballnetwork.go:148
EDITED
and 13:34:18.587 DEBUG   snowball: tick len(votes): 2 snowball.go:58
hmm
13:34:18.587 DEBUG   snowball: calculateTallies: bafyreic5vbgrj4iwyctxqrjerszzew7ks4sflhrsnpkhyixfrvezbvkwvq vote.go:48
13:34:18.587 DEBUG   snowball: calculateTallies: bafyreic5vbgrj4iwyctxqrjerszzew7ks4sflhrsnpkhyixfrvezbvkwvq vote.go:48
13:34:18.587 DEBUG   snowball: calculateTallies: bafyreic5vbgrj4iwyctxqrjerszzew7ks4sflhrsnpkhyixfrvezbvkwvq vote.go:48
13:34:18.587 DEBUG   snowball: calculateTallies: bafyreic5vbgrj4iwyctxqrjerszzew7ks4sflhrsnpkhyixfrvezbvkwvq vote.go:48
13:34:18.587 DEBUG   snowball: calculateTallies: n vote.go:48 …
```
=> set k to the size of the notary group if it is smaller than defaultK

gossip/node.go, gossip/node_test.go, gossip/txsyncer.go
Big bug fixes:
* transaction syncer wasn't sending wrappers, so the abrs were being ignored (so no gossip fallback)
* transaction syncer wasn't validating txs
edge case:
If I'm sitting there with nothing in my mempool but someone comes and asks me to snowball then it's possible I'll never get out of my rut (because I missed Txs, but there's now way for me to get them).
This branch fixes that edge case by starting the snowball (without a preferred) if someone comes in  and asks me for a round and it's >= my current round (but I'm just sitting there). Then I'll start a snowball and ask the network what it thinks so I can sync up my missing Txs.
=> fix broken tx syncer and handle edge case in snowball

cmd/benchmark.go, gossip/benchmark/benchmark.go, gossip/benchmark/benchmark_test.go
* allow setting the timeout
* wait for timeout after the duration to allow transactions to finish
* use the error string for the resultset
=> benchmark improvements

gossip/snowballnetwork.go
I changed this as spaghetti a while back, but this is a better way to read it and I've tested it out locally.
=> change a not and into an or - easier to read

gossip/rounds.go, gossip/snowballnetwork.go, gossip/vote_test.go
Alpha at 0.8 only allows 20% of evil nodes. I'm lowering the threshold to account for 1/3 of the network being evil.
Also adds a bit of logging around snowball params.
=> reduce alpha

Dockerfile
This allows tupelo within the container to bind to ports less than 1024 - while you can typically port forward from a server's < 1024 port to a > 1024 port in docker, the golang autocert automatically binds to 443 with no option to overwrite. The alternate path would require rewriting the golang autocert listener manually and having directly bound to 443 seems reasonable, especially things like address introspection will use the docker port and not the forwarded port
=> Allow tupelo binary to bind to ports < 1024

nodebuilder/nodebuilder.go
wasm uses the `wss` protocol, however, we were previously specifying only `ws` in the broadcast addrs.  Changing it to `wss` resulted in `go-multiaddr` erroring because the protocol is explicitly not registered since it can't be used in go. To solve that issue, this registers the wss protocol as specified https://github.com/multiformats/multiaddr/blob/master/protocols.csv#L26
=> Support WSS address broadcasting

go.mod, go.sum
Pulling this in from https://github.com/quorumcontrol/tupelo/pull/423 separately to test independently of the ~~checkpoint~~ early commit removal
=> up tupelo-go-sdk version

docker-compose.yml
This just adds the delay container brandon found. I can't imagine a scenario where we would want to test a multi-node local tupelo without simulating realworld network connections.
=> add the delay container

docker-compose.yml
this fixes pumba so it actually runs and doesn't require root in the dockerfile. Also locks in the version of pumba for build security.
=> fix up network delay and lock the pumba image in

gossip/node.go, gossip/node_test.go
I opted for the simple thing here rather than adding a chaintree heartbeat. I also didn't worry too much about cacheing the previous send, etc... just wanted to get something in there. What this does now is every 500ms republish the last round with signature, et all as long as the signer is idle.
=> republish completed rounds when not snowballing (and tick refactor)

go.mod, go.sum, gossip/benchmark/benchmark.go
Just adds round tracking and measurement into the benchmarker.
I actually want to refactor this quickly tomorrow morning into two instances of `DurationSet` for the rounds / transactions, but wanted to get this open in case it was useful in debugging.
Depends on https://github.com/quorumcontrol/tupelo-go-sdk/pull/193
=> measure round durations in benchmarker

configs/localdocker/node0/config.toml, configs/localdocker/node1/config.toml, configs/localdocker/node2/config.toml, docker-compose.yml, gossip/benchmark/benchmark_test.go, gossip/node.go, gossip/node_test.go, gossip/rounds.go, gossip/txvalidator_test.go, nodebuilder/config.go, nodebuilder/humanconfig.go, nodebuilder/humanstorage.go, nodebuilder/localnetwork.go, nodebuilder/nodebuilder.go, nodebuilder/nodebuilder_test.go
Reverts quorumcontrol/tupelo#441
Turns out that the case in #441 where the network is saved at different spots is actually happening during benchmarks. We think #442 will fix, this but makes testing new things harder.
=> Revert "Persist last completed round & restore state from it on start"

gossip/snowballnetwork.go
Reverts quorumcontrol/tupelo#429
Turns out this was showing us a bug:
```
but in the idealized version of the bug...
nodes A through D all have 0 txs in their mempool
now nowd E(vil) comes in and pings A with a snowball request for currentRound+1
so A calls B and B calls C and C calls D
but none have any Txs in their mempool
so they all snowball nil
but now they've all started snowballing
so they can never stop
```
=> Revert "allow parallel network sampling"

gossip/node.go, gossip/rounds.go
we found a bug where the fault-detector was showing faults on round publishing. Turns out we were publishing rounds before they were ready to be published in our "republish"
That worked like this:
1. Round decided, moves into background processing
2. The "maybe republish" fires and sees that snowball isn't yet started
3. That calls republish, but the previous round is *not* ready for republishing yet, so we get an old stale state published.
This limits to make sure that if we're *republishing* that we've at least published once.
=> only republish a round after it has already been published

cmd/benchmark.go, gossip/benchmark/benchmark.go, gossip/benchmark/faultdetector.go
The round subscriber would stop pulling from the rounds and block the reporting of the benchmark (sometimes). This moves the unsubscribe from the round subscriber into the go routine where rounds are being handled so that the eventstream isn't held up.
It also cleans up a lot of repeat logging at the end of a benchmark... though there is still a bunch - this is kind of just a step in the right direction.
=> Cleaner end-of-run logging that doesn’t block the pubsub subscriptions

go.mod, go.sum, nodebuilder/no_dial_websocket.go, nodebuilder/nodebuilder.go
This relies on https://github.com/quorumcontrol/tupelo-go-sdk/pull/208 to allow configurable transports.
We noticed that SSL wasn't always updating fast enough for the benchmark network to keep up which would cause signers to connect to "incorrect" peers. This turns of *dialing* from the websocket connection on the signers.
I'm pretty sure this is the behavior we want whether or not SSL could keep up though - we don't want these signers sending stuff over websockets rather than TCP. My very first benchmark showed an improvement - full suite running now.
=> no-dial-websockets

gossip/node.go, gossip/txsyncer.go
from chat:
```
node1_1      | [ACTOR] Recovering actor="nonhost/node-9/transactionsyncer" reason="runtime error: invalid memory address or nil pointer dereference" stacktrace="github.com/quorumcontrol/tupelo/gossip.(*TransactionValidator).ValidateAbr:152" 
node1_1      | [SUPERVISION] actor="nonhost/node-9/transactionsyncer" directive="RestartDirective" reason="runtime error: invalid memory address or nil pointer dereference"
```
https://github.com/quorumcontrol/tupelo/blob/master/gossip/node.go#L148
which calls https://github.com/quorumcontrol/tupelo/blob/master/gossip/node.go#L300
which can happen before https://github.com/quorumcontrol/tupelo/blob/master/gossip/node.go#L166
This puts more logic into the actual *actor* startup as opposed to the node Start method which eliminates race …
=> small refactor to fix a race

configs/localdocker/node0/config.toml, configs/localdocker/node1/config.toml, configs/localdocker/node2/config.toml, docker-compose.yml
In local testing, relying on bootstrap to relay caused tests from local machine to signers to fail frequently.  Given https://github.com/quorumcontrol/tupelo/pull/439 is on the horizon too, this updates the signers to also expose their port to the host machine
=> expose signer ports in local docker-compose

sdk/wasm/jsclient/jsclient.go
When moving the tupelo-wasm-sdk over to the new repo noticed that we were missing the package name for these functional options.
=> fix tupelo wasm client which was just missing a namespace

signer/gossip/mempool.go, signer/gossip/mempool_test.go, signer/nodebuilder/config.go, signer/nodebuilder/nodebuilder.go, signer/nodebuilder/nodebuilder_test.go
This fixes two problems we've seen in the tests:
* The *state* section of an AddBlockRequest (ABR) is non-deterministic because we add state nodes there and so sometimes an abr will have a higher hash than the other. This lets the *test* figure that out so it knows what to assert.
* Occasionally an old node doesn't shut down before the next test starts up. This lets a nodebuilder config have a name (that's currently only used in a test).
On an aside I noticed a Namesapce in nodebuilder config that I didn't see used anywhere so I just marked it deprecated for now.
=> test fixes

sdk/wasm/jsclient/jsclient.go, sdk/wasm/main.go
what it says in the title really. The reason for this is that often in a front-end you want to update locally first and then send off to the network. This allows you to still use a ChainTree for that instead of keeping a shadow data structure around.
=> Add generating AddBlockRequest and sending an ABR to WASM

sdk/gossip/client/client.go, sdk/gossip/client/client_test.go, sdk/gossip/types/validators.go
This ensures that `client.New` & `client.NewWithOptions` automatically set the `NotaryGroup.DagGetter` to itself if not yet set. Also had to update `isOwner` to pass through `NotaryGroup` pointer instead because `DagGetter` is set after the validators are generated.
=> make isOwner usable inside Client

sdk/gossip/client/client.go, sdk/gossip/client/client_test.go, sdk/gossip/types/graftedownership.go
We used to have all the state needed to replay transactions locally in order to reproduce state. However, graftable ownership has changed this and now there might be remote state needed. We don't actually *need* to do this anyway: https://github.com/quorumcontrol/tupelo/blob/bug/remove-playing/sdk/gossip/client/processblocks.go since now the new blocks are part of the state and just getting the latest will work.
=> remove replaying transactions on GetLatest
